#  Generated by Hobo on 7/22/17



Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04"
	config.vm.provision :shell, path: "bootstrap.sh"
	config.vm.network :forwarded_port, host: 8080, guest: 80

# Custom Settings Follow (v1.1)

# Set Static IP. Use IP other than host IP range (if host is 192.168.*.* - avoid it)
config.vm.network "private_network", ip: "10.1.1.33"
# Forward the DB ports for remote connection to MySQL
config.vm.network "forwarded_port", guest: 3306, host: 3306

# Allows directories writable during Provisioning.
config.vm.synced_folder ".", "/vagrant", :mount_options => ['dmode=777','fmode=666']

end
